{% set name = "cmd2" %}
{% set version = "0.8.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2ae9c397bcb8c4ca2a068002407238e56acfce3ed55e67bde35988a100adcdee" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pyparsing >=2.0.1
    - pyperclip
    - six
    - wcwidth  # [not win]
    - pyreadline  # [win]
    - contextlib2  # [py<35]
    - enum34  # [py<34]
    - subprocess32  # [py2k] 
    

test:
  imports:
    - cmd2

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: "Extra features for standard library's cmd module"
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
