{% set name = "cmd2" %}
{% set version = "0.9.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "cffc94ad46425f80dfb243f53f456b11cea3f45e683504a60b64618a6d28b417" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  skip: True  # [py2k]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pyperclip >=1.5.27
    - colorama
    - pyreadline  # [win]
    - wcwidth  # [not win]
    - contextlib2  # [py<35]
    - typing  # [py<35]
    

test:
  imports:
    - cmd2

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: "Extra features for standard library's cmd module"
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
