{% set name = "cmd2" %}
{% set version = "2.3.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "44f9d93bbcd90c6dda70e73db722d6b27b551d98bef28bd82fd14ccbe88d18ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm

  run:
    - python
    - setuptools
    - attrs >=16.3.0
    - colorama >=0.3.7
    - importlib_metadata >=1.6.0  # [py<38]
    - pyperclip >=1.6
    - typing_extensions >=1.6.0  # [py<38]
    - pyreadline  # [win and py<38]
    - pyreadline3  # [win and py>=38]
    - wcwidth >=0.1.7

test:
  imports:
    - cmd2

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extra features for standard library's cmd module
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - tschoonj
