# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Sb9qYkLGE9flntgU4Hy/1ifjaWskrGX7piiSo0/zMDdAw8ldvRw+emumIvjO/XuJzJI8CQSfJM8tXnQ7bH+f+O0Vttf6zYQnrszxjHR2GHPOzsMJR6NBzCaUgwhJm52ZCBcviWZNc2lvnK7F1hsICqvIRIfmlYCIg0FSWF0H2y7pIM6lpx32w4MrIM90I6LEBzDno489ucAmGxB74Cfz9ocNSAlBO220MwB3zHUoi4iuY2QxAv7MyAiojKJodpy8LcfDbhwK7JBWUeDqz1zkMjYprE8NeM8Hu5T+2PQsSmZz7QCkIlLI/x7vsaviXElNp3fgKeM+FqE25RthZyfDEneUwTzULPAueZ2tO7HLOfMP+O0ro/TAk8XjNByRH+6lQVpRqkwn4kFOANKfPTW6M8qT6kYkJDePHkmqQzUkxANwyLjPXBYDzaEvYSVrYziA3peyOr7MD6anxgeW0yZ9M8exoTR+333fW2nzLMNstDrzcuuuBhDUaDI06M2UOHYIMFoZGVZ1UkObAyxB+UrkNUsSAXwvkrKxBwtjt2tdkG44TaBANNRSXI6xLxECIZPO8s2K3Enl4QPGSRgzzbBTc3pka5t0WCkNq3TmrxUnRIJ4uJ06nzJPWjL4g8lpw8E9LrbkfAB7/E8XrLtBUlrm/idNYDw/19YYsN1k/6sAVH4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
