travis:
  secure:
    BINSTAR_TOKEN: 2SIHcbWK5jEoQFC4H12Ov1yyvR5foHwt9iLxhgC7ySincT1yyMi0w10V9HVUXNyotvGXlOc3NroiYpTus4rL7AMVh8eYspwqlWPgqbgu+BORhuTb7BItvwu6GrTb1xD+it8G1moiCyarHDNMCgYbYRG9opAJBof0vFuRjiRN3kOMylaBI4OlLmTYAU3HipePizTCPorfE1LgXnfSr1y1rTr4kkBpo871uYqFoCcknncl0i5u7FQSxAziwiqwE59/1A7JptvdTb8c7mPN31NMmopwhNCTyZNkJoAPY6J701RRYgKp+kDHe+S3ehfw8YIQy1Kgp7oiq2lhjg8Ri/RLulTagFAxQEr2b2Xiig6nHnlqb4y2sJbg8824Pr7+uhQuhBZuz2vpIZBHv+xIlwDcoLwoNSyV9LPwKFgYp84Ud24PFWBn2o6sodnWj6MgSZ16DpSgZebZzuSqxTlpVZtU2IASBlmcl3MehQMDN7uCwARpjSlqYUzd7Np81UPMqf6gk8AbOq+4rsytVAA9th7I6mkUogyEXJOIF8mEQ3xsZAXybFFs4yib1XXu1Qda6DOch5Ub7QpYNdDGLTcGINJXH12BFtWEl+9XT27bWOrixOSbVb7HtrQXIekSit96xiAkZZzPCbvsR4AeoX3bSRPRU2/pPmXlGwBWCH43Wxn1ShA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
