travis:
  secure:
    BINSTAR_TOKEN: oXMPfjZbpncooGnRPYn0WeHQz4LuGbS45UxIynC610znJsHRj/hCXjkBHrVf1SnVp4fpiqL+cDaq8+tc7aOvwsi8MBp0KXEadmOGlHlKYElspC3bjn75khWUH9Y07umgK1pPIKZaZj7eUQXSL2PLKpUvanU2XdjMcYmYWXLP5+OghV1qANsErqnsSMOzZqWSjvu8x9X7bRFO9XTbsl4LpXqJV1WQTka7VK9S3Ed1CjFY4MWZMMJiJy9xHUSJYiJZrCpxzEQKWuvgYRKRe+fGNU19tqm9DTOUr1330pnS5FZHhFaC7AvddiT0OCjw+BtBE0MoAYJjnPC2K8yPfbStYydFdbA3u8z9w0I/wiIXeqSYXSu7qS8HFicDyjG1U7RQgrtGI5SepVNdPsOqDZnjmw4h23yvFFawYLyL1DbmIedYTTqnoIUFXpFdK4B+r5EtDTdRNaImp2mz27gEUjuAEQj+z5b1jvMWJXyuq4AA+5BLAq0E9atOABQcyO1yLB8EsCy3pvjp3H0KP5pvksKmByUPySvCqS1uAALEDvAcRx7oZUsvI61Cqe6CRTDH0leya4NKGiwecJI13naeisqPjSog5L3oyjViBZ/LVDwiaJf/Nrf0boyis52JQKjcMU6K5YWkeBQzsWObzxEk+1itx03h044Lr3eRv8PXow/UVec=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
