travis:
  secure:
    BINSTAR_TOKEN: N3y8WcLlbqWvmNDeo+LlWsB5RYPEZWmMjweWLiue6JVSayKWzrwZhyKae7nuz+qY7cLq+syp9av+fP6iKd8URbllSUy/IU57AI9jz3ejdMj1ZYZyz0VRULlyYXCMotg8NcQPqe7SFaXX+qmn6NagNPqg2bNZp5XrL2O9mRVnLbbwKwKPjvsfpwMs6qIJy8+ttRn7Qs6ZAtOr5YCw0y5GE7LcA+zEBOwRuYqofdeb7YGJ0Y1eii2hC1AqjBUKlKhWX28htptFDqDyptUasM+VFAqBFn7TywiEY/8I5zGgUswYJmovB7Av7aDpbKV8CeW50pzqjk8lW7jSS+whnEsexK1zDW7izr3gd1TQxKDuaE5469qiYPPzROY++XTe/MNYw9vfj5VrYptVJPqsSvq1DUMN8Kr8bGlZicbfB/qji737WbWg5m14q17uqFvpX7AvoCk30MF4PgqD1gH0aBr14iKq5h4suVqmSAfcu4J1DQu9Dd+fvKY/+HCsQciLK1jH0sSL4pXu7dZE+/wI6uPGox0TY33eQuZ7ZHzZC2dvhc9ZCG7lE3qB+t7heBifJU4oOWqH9uGQjRNLCwqgjteqpmC79KCFq/EUyVfm87wlN/7qdqwGetAveQefcpcVEGHVuD+TPHmY4mpi+Q4vL8u6vCPvqECqCZz/7uC0mPDFxRU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
