travis:
  secure:
    BINSTAR_TOKEN: Sb9qYkLGE9flntgU4Hy/1ifjaWskrGX7piiSo0/zMDdAw8ldvRw+emumIvjO/XuJzJI8CQSfJM8tXnQ7bH+f+O0Vttf6zYQnrszxjHR2GHPOzsMJR6NBzCaUgwhJm52ZCBcviWZNc2lvnK7F1hsICqvIRIfmlYCIg0FSWF0H2y7pIM6lpx32w4MrIM90I6LEBzDno489ucAmGxB74Cfz9ocNSAlBO220MwB3zHUoi4iuY2QxAv7MyAiojKJodpy8LcfDbhwK7JBWUeDqz1zkMjYprE8NeM8Hu5T+2PQsSmZz7QCkIlLI/x7vsaviXElNp3fgKeM+FqE25RthZyfDEneUwTzULPAueZ2tO7HLOfMP+O0ro/TAk8XjNByRH+6lQVpRqkwn4kFOANKfPTW6M8qT6kYkJDePHkmqQzUkxANwyLjPXBYDzaEvYSVrYziA3peyOr7MD6anxgeW0yZ9M8exoTR+333fW2nzLMNstDrzcuuuBhDUaDI06M2UOHYIMFoZGVZ1UkObAyxB+UrkNUsSAXwvkrKxBwtjt2tdkG44TaBANNRSXI6xLxECIZPO8s2K3Enl4QPGSRgzzbBTc3pka5t0WCkNq3TmrxUnRIJ4uJ06nzJPWjL4g8lpw8E9LrbkfAB7/E8XrLtBUlrm/idNYDw/19YYsN1k/6sAVH4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
