travis:
  secure:
    BINSTAR_TOKEN: PdgSWOLrT3pYMwN9MMs0b5bK9/SFCbWbdmzrmLVHrmpxx6v5NuDQi7md/fyc/I6NfKnYIx3OZl/fPT18tR3fEUtLmkc56LwJMJa3Zmj5A68Bj+0GwQmkY96Bf0MPwhh2T7NOFAZYfoYdUdqUzE+L5vACGP8iE6LkXZ1JBt/t5mCRJlGpdTmWg0F0Rkl0wVRRRx8KSouG6gzSOaPMUVf8obPC5UzMC4oGkOtWxJ/VzRU2szRICV5CXBrlOmAxwAS/YC8+UdfdihxrKkpUTcnSl6b3fqEXTDZ+dN7tFXfMaKUNf5Iwql2Axhmvvzh/mR3d6jV9AzGOUVzDz357/u9qDdQaD+IjoVcFDr60/lldzG8ZbkUoMQvtROjbFmFzj2AkyANTfMd6v4xdZGx15sSFvfOAhPNSYA7Ldr9C23EWof0wUa23ao1JFKWuR/JoXPPj2T98HlBqQKXQY0buGgj92xYJ4uXHJSAB7o96L7rqRx8m1ZhuaHE1JLUl8EQTmokf4Q1WHnnD/aJLiPJsPPgvERNdvP7oPTZl+eJFKyBqp1lSfj9PkFQAOTcZNkpqTTpYZKZAnPWYQelkdxPSvtMbHKh87V8K5QpdujxBACPO3LHjCjeZb2TIm/HA4/PkX2xMZKY85L3V3Bn1mIuSPZZF1n156d/mVB73O0JJtUv1PfY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
