travis:
  secure:
    BINSTAR_TOKEN: FE8+7aTQSNoTJTYrL1nQK8flv66ZSZpE9CgbGnr2pQj7qMsEWf8ve6LFKz4hDimKDYToimDpBjDKD4jFQeJShnNG7d9x7uopnO9jSEgwHBV3SbDSZMDpVYCv1fNjljEQ/INaKU2fSUe2HDQInUCcQ3VhFnFus7uWe+GI4p5DZJQF7RLVXWgFFRyyekdO5zEHHN6Y0Mpwo6D0oHVLh0fM80VZEAP/S45IfTgNKssmyvRMwYNtzZvWM56oCbnRvz1kXtksflj3ae9QA9Kmod5nHZd+Ll0WvNayNN0RQUch5/Ye7AFTpKlmzbNmwurokFUKNkViXxOYwTtXmzb9Bww93TKjdnjkIKIfayzgl/n5IOLFYDOfi+qLvFZRE5qiYwQ2jdbqijRekvuIJOJZqKsrfIVVAXzGHzkqp6LIJw0YmLkiL2onraKJJlUu3yIJlZreW+/qBPsef7OLIBXxJ5775JCDWdMveErfQaRz2CSsFT+PGz1fkwjBmc6XnpXZqboCwx+si7aga5GLvB5H61fvcYiPh0cx9QYiSOk8HCA6HjCooPzeqTAHH/ffh1R13D0//VQZRZoa8cAeK3eaBDGpdIyFrf0IsuMmWnNbHg8I3cgszjF8qRo3+HRIRASxVMrE4SuYk1IVFCRBRU9MayP6BXIRQ2SknWe56+jTYVo1pkY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
