travis:
  secure:
    BINSTAR_TOKEN: hTbqln0/L3vEo9Z8V1bzUPTExypYBRMzpXZOpsDgEpZQ18v8i9fiOY5QZ4Ob45+M9bygYXhrc5VRlhrmNh7Aheh4hdFjkqsZ8O78Dsytd4KmZrqZfG8h2O78apYwOg3L2wee17z9t//ouW0H3dPgkLc3LTMhJi/un54Ebu+CC+CeExalKYR5phVr0bHOIOD6F6HOK0bcsX4WIM/39Ov2m0s2/f4Nh8MCerP6iR/6Gr6FkvandCxIhLXIG8lhD+1atTfYvI4AEYMVZ/CbRa/PRuztHeIuRrDwuQJ7gXKiEZELifaM3ssaprFTRVUjUP89nWVebGGaOUGXxGnex/2gS5ArOvq42GSoDcPZ7BI4/LqWext5CV1vAVC2AWUYc5LdAzksX2V1q+TgDYGda79RsxsVjTS4BG/QAhqFqV4SNPBk9otrvhSr71hwoP0ThIOG8FFCvmj9wo1p3lmD+m+9Ctk3x5P1deTrdtJCkCdoySfjQWjEXQnrdpV36aoJjWaZd+CgVDwWyUklWWYJ2kMEoWI7L0dLm6SE+u1fKQmhgD39dD7kupFxRgYTl7AyVmYYzzOWGo6TJEjAEZmqoRF3tXnwPJD2SZ/7bjy2f+wkq9dTuRgb6d3L9C0vkST0h76cfl6YOqujHfhtp8TtKNk4+2ZK2g6fmIwVE6WlXeWZO6w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
