travis:
  secure:
    BINSTAR_TOKEN: yfYb3EPgm/6Gkinp+sy/hbDCXC03CV0NH4tRhLKZLRkrkOlQbc1h7F6DgXFX98h9z9j0/PonZyJWTrKa+hKCScJn3t1/Dm+zQHi2LEBqlE8pyMwA3kJenDvwudOhD4/ufAzImMCfZ7zYZonG6uveDCnqZ1zx+fc87IqAhA17dlzzcfqToeDey0dl0qzbYmmOxvNLAlJ4gcO7hnk63dPiVM3VN9x4Ov2KEYWJSuhX/GM+HtKu34cl+yIzoDNthCifd/U4SYWI8ymiFi7r6zQQOtC9pfAw+NsJ9sd8klDeI2v51pjOGigW96mdBXmPloihLLT7/FrM1KXqUKB4g8hmp89McOOh1grUKCF44Vw6Oyjxa4W9ADt0eFMUDdpN1lU2AvT7UYu/LX6psAEcHNPfh63A9hbrh9CLd/enMyKbRKwCozEiYwOEdEUC/jcZyUpxGnAfJlLxK11A6+n6Q2UTBGmkQryBSUdO4AKhAUQ8J9DMHqbBelwFw6gVLT3n3TmB2OoboSGUZNiFRe4UA5LTSYDIREnu89zfsE47ssEjPGXBZAbXKSA05S+YBp6ZV/WK4stJC2l6QUR46vDujMt0VMHWFJ4CoxFi9YtxQJouVLVpCNTnfp8+8NQHCT9Q4mJgiv9Fce8tn9aRSAF+ocIWR6F5e9B+3oRJPrKxJCF7Wg0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
