travis:
  secure:
    BINSTAR_TOKEN: jFeO7uZ+HWGoRAea/XtSeIVhwdQPoXdyShMIEbWwcn7IwZzY6a5TLiUJEfgITXOFufkQy6SujExarBXFU0mLHqBSvEHTDhS4UnQ2iMb7RBoV2xmfrzJab6Nt8S9XljAYkXKZBmQA25twcQ57E3kMe6NRNyAx4z0TI7JqQhEFG5LxJiW2iUt9l4B+Ey87EEd0JKUqyo0RJ3FBVXkkMNqcIaucgUvqkTdCt+RJ4PapnLiFmleVr5YiYF8LkHQBt2RAXvZbfsa48av8iJK4dfb4laXepq/sTcmxINknuw0QNz8YxRhnnMzRQYrM1ShH1gptN+7ao+zvZlAIdl6ADeKFs9WUA5dt0AtrOnzB4yYfwDSAacVqa8oJSZHLwUd7Wjv31P4Ugr8ZUqrau6HoW7MBtuz87oTA3KO0vLTPNCkYHgvPCfEp079uX3URJ71oiTorFMz8NaLMkIFqmOX4GU+55iUDExHfMmStM6TP2jyaJHN3senRRHyC2dARwhGqxhfPcQEbTroIck49XmNG9ohMAIeLWVIxT2JhU9MZDFVp3f2ULiNsGMMRGPLYobjagwUtB/ipLHJU282+Vwd4XLUo4GSj3OZzQAPnJMnw6Xzv7Kkq6sa/T6YoBxaEW/+XpWMOpYrtv4JUgZB1rKsjYAvXbJZ79nf9mQx316nvagyLxhE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
